datadir: ./data

spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  thymeleaf:
    cache: false

