datadir: ./data

spring.data.requery:
  modelName: org.springframework.boot.autoconfigure.data.requery.domain.Models.DEFAULT
  batchUpdateSize: 50
  statementCacheSize: 512
  tableCreationMode: CREATE_NOT_EXISTS
